pub mod array_2d;
pub mod index;
pub mod iter;
pub mod slice;
pub mod split;
pub mod utils;
pub mod vec_2d;
pub use index::{GetElemRef, GetElemRefMut};
pub use slice::{Shape2D, Shape2DExt, Slice2D, Slice2DMut};
pub use split::{Split, SplitMut};
